[package]
name = "zesty_engine2_test_utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
float-cmp = "0.9.0"
zesty_engine2 = { version = "0.1.0", path = ".." }
